spring:
    
server:
  port: 8004

# Logging options
logging:
  dump-headers: false
  level:
    org.springframework: INFO
    aero.sita: INFO

# App properties
app.name: Smart Path Relay
app.version: 1.0

# webhook label
app.agent.label: Smart Path Relay
app.agent.apikey: sitalab.!s.th3.b35t

# Interface to be used, options are: websocket / webhook / both
app.use.interface: websocket

# Type of enrolment, options are: true (use biometric token API), false (use enrolment API)
app.use.biometric-token: false

# WebHook properties
app.webhook.provider.url: https://provider-services-staging.sitalab.io/api/v1.0/webhook
app.webhook.provider.apikey: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJtb2JpbGUtZHRkIn0.4EEciRiOb-fFCmNnFhMdqYYDjKekW7AQyWYb6looEMdOzBp3yp30C0NcUx6Ni55y80hWZYUWK2m3FY1pJrUlUQ
app.webhook.callback.url: https://feed-service.sitalab.io/api/v1.0/feed/sph

# Gallery Service websocket URL, message size in MB and WS heart beat and connection retry intervals
app.feeder.ws.url: wss://gallery-services-staging.sitalab.io/gallery
app.feeder.ws.message.size: 1
app.feeder.ws.connect.interval: 30
app.feeder.ws.heartbeat.interval: 45

# Smart Path Hub access token
# //57.1.226.8:8443/oauth/token?grant_type=client_credentials
app.feeder.access.token.url: https://login.microsoftonline.com/sitaspm.onmicrosoft.com/oauth2/v2.0/token
app.feeder.grant_type: client_credentials
app.feeder.client_secret: _4_Nt5b3dX~vkLzhXBO0b3_~J5P8V7O_f.
app.feeder.client_id: 6bc3aeb0-04cb-47cd-b805-1b2554391ff2
app.feeder.scope: https://sitaspm.onmicrosoft.com/mcs/api/.default

# Smart Path Hub enrol token and registration
app.feeder.sph.url: https://57.188.61.129/biothenticateRestSvc/rest/enrolmentapi/v1/enrol/
app.feeder.sph.paths: token,registration

app.mask.logging: false

# Swagger
swagger.enabled: true

---

spring:
  config.activate.on-profile: local

# Logging options
logging:
  level:
    aero.sita: DEBUG

# Interface to be used, options are: websocket / webhook / both
app.use.interface: websocket

# Type of enrolment, options are: true (use biometric token API), false (use enrolment API)
app.use.biometric-token: false

# WebHook defaults set to local services
app.webhook.provider.url: http://localhost:8000/api/v1.0/webhook
app.webhook.provider.apikey: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJtb2JpbGUtZHRkIn0.4EEciRiOb-fFCmNnFhMdqYYDjKekW7AQyWYb6looEMdOzBp3yp30C0NcUx6Ni55y80hWZYUWK2m3FY1pJrUlUQ
app.webhook.callback.url: http://localhost:8004/api/v1.0/feed/sph

# Gallery Service websocket URL, message size in MB and WS heart beat and connection retry intervals
app.feeder.ws.url: ws://localhost:8002/gallery
app.feeder.ws.message.size: 1
app.feeder.ws.connect.interval: 30
app.feeder.ws.heartbeat.interval: 45
app.feeder.ws.disable.ssl: true

# Smart Path Hub access token
# //57.1.226.8:8443/oauth/token?grant_type=client_credentials
app.feeder.access.token.url: https://login.microsoftonline.com/sitaspm.onmicrosoft.com/oauth2/v2.0/token
app.feeder.grant_type: client_credentials
app.feeder.client_secret: _4_Nt5b3dX~vkLzhXBO0b3_~J5P8V7O_f.
app.feeder.client_id: 6bc3aeb0-04cb-47cd-b805-1b2554391ff2
app.feeder.scope: https://sitaspm.onmicrosoft.com/mcs/api/.default

# Smart Path Hub enrol token and registration
app.feeder.sph.url: https://57.188.61.129/biothenticateRestSvc/rest/enrolmentapi/v1/enrol/
app.feeder.sph.paths: token,registration

app.mask.logging: false

# Swagger
swagger.enabled: true
